/*
 * 0x22 - Tell Display sending speed data 
 * 11x11 - Tell Display System Check OK
 * 0x2 - ERROR SENSOR FWRP FAULT
 * 0x3 - ERROR SENSOR FWCP FAULT
 * 0x4 - ERROR SENSOR FWLP FAULT
 * 0x5 - ERROR SENSOR LSSP FAULT
 * 0x6 - ERROR SENSOR BLSP FAULT
 * 0x7 - ERROR SENSOR BCSP FAULT
 * 0x8 - ERROR SENSOR BRSP FAULT
 * 0x9 - ERROR SENSOR RSSP FAULT
 */

 
